### ISSUE TITLE
Initial Configuration Module

### ISSUE THREAD

**Issue by Angelin01** [Angelin01/pod-director#2]
# Initial Configuration module

We'll need a way to configure the application.

I have some experience with [Figment](https://github.com/SergioBenitez/Figment) combined with Serde. I think it should
suffice.

The initial requirements are:
- Read a YAML file
- It must support the groups structure we established:
```yaml
groups:
  bar:
    nodeSelector:  # node selector labels
    affinity:  # pod affinity
    tolerations:   # to handle taints
  bazz:
    nodeSelector:  # node selector labels
    affinity:  # pod affinity
    tolerations:   # to handle taints
```
- Until we define the actual format of the `nodeSelector`, `affinity` and `tolerations` blocks (and their final names),
  the value can be a placeholder list of strings
- The default configuration file path should be either an established well known path or something easy to remember,
  like a specifically named file in the current working directory.
- One should be able to change which file is read using an environment variable
- All configurations should also be configurable by environment variables (Figment handles this), which have precedence
  over the config file
- Return a struct that holds all of the configuration for the entire application

We'll create further settings, like for log levels, mode (enforce or log only, if we implement this), etc as we go.

In a future task we can also consider hot reloading.
